## Numerical Data manipulation with python and numpy
Numpy is very fast since the code has been optimised to run using C. C is a lower level language compared
to python and it's also much faster than python. Vectorization causes this speed benefit and numpy achieves this through broadcasting

In [2]:
# Importing numpy
import numpy as np

In [14]:
# Main type of numpy is ndarray
# 1d array aka a vector
arr1 = np.array([4,5,6])

# 2d array aka a matrix
arr2 = np.array([[1,2,3],
               [4,5,6]])
# 3d array aka matrix
arr3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
                 [[10,11,12],
                 [13,14,15],
                 [16,17,18]]])


In [15]:
arr1

array([4, 5, 6])

In [16]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [19]:
# Check the type and data type of the numpy arrays
type(arr1), arr1.dtype

(numpy.ndarray, dtype('int32'))

In [22]:
# Check shape and array size
arr2.size, arr2.shape

(6, (2, 3))

In [23]:
arr3.size, arr3.shape

(18, (2, 3, 3))

### Creating arrays
- np.array()
- np.zeros()
- np.ones()
- np.random.randint(10, size =4)
- np.arange(2,12,2)
- np.random.rand(3,5)
- np.random.seed(0)
- np.unique()

In [25]:
an_array = np.array([1,2,3])
an_arrayrray

array([1, 2, 3])

In [29]:
# Create an array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
# Create an array of ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
# Create a random array
np.random.randint(20, size=5)

array([7, 6, 1, 5, 1])

In [32]:
# Create a array in a certain range
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
# Create a random array of floats between 0 and 1
np.random.rand(2,2)

array([[0.9058978 , 0.81639997],
       [0.46347142, 0.44069309]])

In [37]:
# Create random arrays
np.random.random((2,3))

array([[0.65223603, 0.12916142, 0.19514381],
       [0.38785823, 0.14764164, 0.81007462]])

In [38]:
# To keep the random numbers generated and for the sake of consistency, np.random.seed() can be used
np.random.seed(5)
np.random.rand(2,2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091]])

In [40]:
# Find unique values in numpy array
np.unique(arr3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

### Indexing arrays and matrices

In [42]:
arr1

array([4, 5, 6])

In [45]:
arr1[0], arr1[2]

(4, 6)

In [46]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr2[0] # returns elements in the first row

array([1, 2, 3])

In [52]:
arr2[1] # returns elements in the second row

array([4, 5, 6])

### Manipulating arrays and comparison operators

In [54]:
# add arrays
arr1 + np.zeros(3).astype(int)

array([4, 5, 6])

In [59]:
# multiply arrays
arr1 * np.zeros(3)

array([0., 0., 0.])

In [60]:
ones = np.ones(3)

In [61]:
arr1 - ones

array([3., 4., 5.])

In [62]:
# find log of an array
np.log(arr1)

array([1.38629436, 1.60943791, 1.79175947])

In [64]:
# find exponential of an array
np.exp(arr1)

array([ 54.59815003, 148.4131591 , 403.42879349])

In [65]:
# raise an array to a certain power
arr1**3

array([ 64, 125, 216], dtype=int32)

In [67]:
#square an array
# arr1 ** 2

np.square(arr1)

array([16, 25, 36], dtype=int32)

In [70]:
# find reminder or modulus
arr1 % 5

array([4, 0, 1], dtype=int32)

In [71]:
# Divide two arrays
arr1/ones

array([4., 5., 6.])

In [72]:
# Divide using floor division
arr1 // ones

array([4., 5., 6.])

In [76]:
# add a scalar quantity to Array
arr1 + 2

array([6, 7, 8])

In [77]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
# add a scalar quantity to Array
arr2 + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [79]:
arr1 + arr2

array([[ 5,  7,  9],
       [ 8, 10, 12]])

In [80]:
arr2.shape

(2, 3)

In [81]:
arr1.shape

(3,)

In [84]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [83]:
arr1 + arr3

array([[[ 5,  7,  9],
        [ 8, 10, 12],
        [11, 13, 15]],

       [[14, 16, 18],
        [17, 19, 21],
        [20, 22, 24]]])

In [85]:
# raises an error because of shape mismatch
arr2 + arr3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

### Aggregation

In [86]:
np.sum(arr1)

15

In [87]:
arr1

array([4, 5, 6])

In [90]:
big_array = np.random.random(100000)
big_array.size

100000

In [91]:
# comparing python sum to numpy sum
%timeit sum(big_array) # python sum
%timeit np.sum(big_array)

33.9 ms ± 1.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
104 µs ± 1.37 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [93]:
# find mean
np.mean(arr1)

5.0

In [94]:
# find standard deviation: measure of how spread out number are from the mean
np.std(arr1)

0.816496580927726

In [95]:
# find the variance: average squared differences of the mean
np.var(arr1)

0.6666666666666666

In [97]:
# standard deviation is the square root of variance
np.sqrt(np.var(arr1))

0.816496580927726

### Transpose

In [100]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
arr2.shape

(2, 3)

In [103]:
transposed_arr2=arr2.T
transposed_arr2

array([[1, 4],
       [2, 5],
       [3, 6]])

In [104]:
transposed_arr2.shape

(3, 2)

### Comparison operators

In [115]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
arr1 < arr2

array([[False, False, False],
       [False, False, False]])

In [118]:
arr1 >= arr2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [119]:
arr1 > 6

array([[False, False, False],
       [False, False, False]])

In [120]:
arr1 > 4

array([[False, False, False],
       [False,  True,  True]])

In [121]:
arr1 == arr1

array([[ True,  True,  True],
       [ True,  True,  True]])

In [127]:
arr1 == arr2

array([[ True,  True,  True],
       [ True,  True,  True]])

### Sorting arrays

In [128]:
# Random array
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[6, 0, 8],
       [6, 0, 1],
       [4, 5, 0],
       [3, 0, 4],
       [4, 6, 0]])

In [129]:
# sort array
np.sort(random_array)

array([[0, 6, 8],
       [0, 1, 6],
       [0, 4, 5],
       [0, 3, 4],
       [0, 4, 6]])

In [130]:
# use argsort to return the indices that would sort an array
np.argsort(random_array)

array([[1, 0, 2],
       [1, 2, 0],
       [2, 0, 1],
       [1, 0, 2],
       [2, 0, 1]], dtype=int64)

### Use case

In [134]:
# Turn an image into numbers
from matplotlib.image import imread
tesla = imread('https://www.clipartkey.com/mpngs/m/303-3033082_tesla-car-png-tesla-david-dobrik-model.png')
tesla

array([[[0.96862745, 0.96862745, 0.96862745, 1.        ],
        [0.96862745, 0.96862745, 0.96862745, 1.        ],
        [0.96862745, 0.96862745, 0.96862745, 1.        ],
        ...,
        [0.96862745, 0.96862745, 0.96862745, 1.        ],
        [0.96862745, 0.96862745, 0.96862745, 1.        ],
        [0.96862745, 0.96862745, 0.96862745, 1.        ]],

       [[0.96862745, 0.96862745, 0.96862745, 1.        ],
        [0.96862745, 0.96862745, 0.96862745, 1.        ],
        [0.96862745, 0.96862745, 0.96862745, 1.        ],
        ...,
        [0.96862745, 0.96862745, 0.96862745, 1.        ],
        [0.96862745, 0.96862745, 0.96862745, 1.        ],
        [0.96862745, 0.96862745, 0.96862745, 1.        ]],

       [[0.96862745, 0.96862745, 0.96862745, 1.        ],
        [0.96862745, 0.96862745, 0.96862745, 1.        ],
        [0.96862745, 0.96862745, 0.96862745, 1.        ],
        ...,
        [0.96862745, 0.96862745, 0.96862745, 1.        ],
        [0.96862745, 0.968627

In [138]:
print(type(tesla))

<class 'numpy.ndarray'>


In [139]:
tesla.shape

(489, 900, 4)